version: "4.7"

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mccs-db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./.jmix/postgres:/var/lib/postgresqldata