name: Feature Request
description: Request for a new Feature
title: "[Feature Request]: "
labels: ["feature", "request"]
assignees:
  - herman-sheppard
body:
  - type: markdown
    attributes:
      value: |
        Welcome to MCCS Feature Requests
  - type: textarea
    id: feature-description
    attributes:
      label:  Feature Description
      description:  Describe new Feature.
      value: |
        As a ...
        I want to ...
        So I can ...
    validations:
      required: true