name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'temurin'
          java-version: 17

       - name: Run Tests
         run:  ./gradlew test

       - name:  Publish Test Report
         uses: mikepenz/action-junit-report@v3.0.1
         if: always()
         with:
           report-paths: '**/build/test-results/test/TEST-*.xml'
