name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mccs-db
          MAIN_DATASOURCE_USERNAME: db_user
          MAIN_DATASOURCE_PASSWORD: db_password
        options: >-
          -- health-cmd pg_isready
          -- health-interval 10s
          -- health-timeout 5s
          -- health-retries 5

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Run Tests
        env:
          MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mccs-db
          MAIN_DATASOURCE_USERNAME: db_user
          MAIN_DATASOURCE_PASSWORD: db_password
        run:  ./gradlew test

      - name:  Publish Test Report
        uses: mikepenz/action-junit-report@v3.0.1
        if: always()
        with:
         report-paths: '**/build/test-results/test/TEST-*.xml'
